### ISSUE TITLE
Does TaSIL require the parameters of the expert policy?

### ISSUE THREAD

**Issue by TianhongDai** [unstable-zeros/TaSIL#1]
Hi,

Thanks for your great work! I have one question after reading the paper. Could you help me to address it, please?

Could I know if Taylor Series Imitation Learning (TaSIL) requires the parameters of the expert policy to calculate the augmented loss term, please? Because from the code: [https://github.com/unstable-zeros/TaSIL/blob/main/imitation_learning/__init__.py#L49](https://github.com/unstable-zeros/TaSIL/blob/main/imitation_learning/__init__.py#L49), it seems the corresponding loss term need the parameters of the expert policy. 

And if it requires the parameter of the expert policy - why don't we just use the expert policy directly?

Looking forward to your reply!

Best Regards

**Comment by unstable-zeros** [comment]
Note that both the Jacobian and Hessian are taken with respect to the state x, not the parameters theta, so for the basic implementation, we only need access to a differentiable expert policy (not the parameters defining it).  For example if you had a (nonlinear) model predictive controller implemented in JAX, then you could use that as the expert, and this is an expert that isn’t a neural network with parameters defining it.

We also show in the appendix how the Jacobian can be approximated efficiently via finite-differencing and random projections under the assumption you can only query the expert but not its Jacobian.

Hope this helps!

Best,
Nik

-------------------------------------------------
Nikolai Matni
Assistant Professor
Department of Electrical and Systems Engineering
University of Pennsylvania
https://nikolaimatni.github.io

**Comment by TianhongDai** [comment]
@unstable-zeros Hi Nik,

Thank you so much for your quick reply! It solves my concerns now. 

Thank you so much again!
